name: Pulumi Pull Request

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/pulumi/**'
  workflow_dispatch:

jobs:
  check:
    name: Check Node.js
    uses: ./.github/workflows/node-check.yaml

  preview:
    strategy:
      matrix:
        profile: [ 'dev', 'staging', 'prod' ]
    name: Pulumi Preview
    needs: check
    uses: ./.github/workflows/pulumi-preview.yaml
    with:
      profile: ${{ matrix.profile }}
    secrets: inherit
