name: Pulumi Preview

on:
  workflow_call:
    inputs:
      profile:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      PULUMI_ORG_NAME:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true

jobs:
  preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: pnpm install
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: ${{ secrets.PULUMI_ORG_NAME }}/infra/${{ inputs.profile }}
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: infra/pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
